In [76]:
import numpy as np
#import pandas
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
import matplotlib.pyplot as plt
%matplotlib inline

In [77]:
training =  np.loadtxt("datasets/poker-hand-training.txt", delimiter=",")
#print(len(training))
tx = training[:,0:10]
ty = training[:,10]
#print(tx)
print(tx.shape)

(25010, 10)


In [78]:
encoder = LabelEncoder()
encoder.fit(ty)
encoded_Y = encoder.transform(ty)
#  one hot encoded
dummy_y = np_utils.to_categorical(encoded_Y)
print(dummy_y)



[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [79]:
model = Sequential()
model.add(Dense(100, input_dim=10,  activation='relu'))
model.add(Dense(100, input_dim=10,  activation='relu'))
model.add(Dense(75, input_dim=10,  activation='relu'))
model.add(Dense(50,  activation='relu'))
model.add(Dense(50,  activation='relu'))
model.add(Dense(25,  activation='relu'))
model.add(Dense(25,  activation='relu'))
model.add(Dense(10, activation='softmax'))



In [80]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [81]:
model.fit(tx,dummy_y , epochs=100, batch_size=5)

Epoch 1/100
25010/25010 [==============================] - 13s 503us/step - loss: 0.9900 - acc: 0.5085
Epoch 2/100
25010/25010 [==============================] - 7s 267us/step - loss: 0.9696 - acc: 0.5307
Epoch 3/100
25010/25010 [==============================] - 7s 264us/step - loss: 0.9568 - acc: 0.5409
Epoch 4/100
25010/25010 [==============================] - 7s 270us/step - loss: 0.9517 - acc: 0.5523
Epoch 5/100
25010/25010 [==============================] - 7s 266us/step - loss: 0.9424 - acc: 0.5521
Epoch 6/100
25010/25010 [==============================] - 7s 267us/step - loss: 0.9390 - acc: 0.5566
Epoch 7/100
25010/25010 [==============================] - 7s 271us/step - loss: 0.9324 - acc: 0.5611
Epoch 8/100
25010/25010 [==============================] - 7s 270us/step - loss: 0.9237 - acc: 0.5712
Epoch 9/100
25010/25010 [==============================] - 7s 270us/step - loss: 0.9168 - acc: 0.5763
Epoch 10/100
25010/25010 [==============================] - 7s 275us/step - loss:

25010/25010 [==============================] - 6s 241us/step - loss: 0.1435 - acc: 0.9607
Epoch 81/100
25010/25010 [==============================] - 6s 238us/step - loss: 0.1400 - acc: 0.9639
Epoch 82/100
25010/25010 [==============================] - 6s 238us/step - loss: 0.1317 - acc: 0.9681
Epoch 83/100
25010/25010 [==============================] - 6s 235us/step - loss: 0.1297 - acc: 0.9668
Epoch 84/100
25010/25010 [==============================] - 6s 239us/step - loss: 0.2837 - acc: 0.9163
Epoch 85/100
25010/25010 [==============================] - 6s 236us/step - loss: 0.2689 - acc: 0.9212
Epoch 86/100
25010/25010 [==============================] - 6s 258us/step - loss: 0.2328 - acc: 0.9327
Epoch 87/100
25010/25010 [==============================] - 7s 260us/step - loss: 0.1067 - acc: 0.9752
Epoch 88/100
25010/25010 [==============================] - 7s 261us/step - loss: 0.1344 - acc: 0.9662
Epoch 89/100
25010/25010 [==============================] - 7s 267us/step - loss: 0.37

In [82]:
testing =  np.loadtxt("datasets/poker-hand-testing.txt", delimiter=",")
print(testing)

[[ 1.  1.  1. ...  1. 12.  0.]
 [ 3. 12.  3. ...  2.  5.  1.]
 [ 1.  9.  4. ...  3.  9.  1.]
 ...
 [ 1. 11.  4. ...  2.  7.  1.]
 [ 3. 11.  1. ...  2.  8.  1.]
 [ 2.  5.  2. ...  3.  3.  2.]]


In [85]:
test = tx = training[:,0:10]
pred = model.predict_classes(test)
