In [37]:
import numpy as np
#import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
import matplotlib.pyplot as plt
%matplotlib inline

In [38]:
training =  np.loadtxt("datasets/poker-hand-training.txt", delimiter=",")
#print(len(training))
tx = training[:,0:10]
ty = training[:,10]
#print(tx)
print(ty.shape)

(25010,)


In [39]:
encoder = LabelEncoder()
encoder.fit(ty)
encoded_Y = encoder.transform(ty)
#  one hot encoded
dummy_y = np_utils.to_categorical(encoded_Y)
print(dummy_y)



[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [40]:
model = Sequential()
model.add(Dense(100, input_dim=10,  activation='relu'))
model.add(Dense(50,  activation='relu'))
model.add(Dense(10, activation='softmax'))



In [43]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [45]:
model.fit(tx,dummy_y , epochs=100, batch_size=5)

Epoch 1/100
25010/25010 [==============================] - 5s 185us/step - loss: 0.8909 - acc: 0.5908
Epoch 2/100
25010/25010 [==============================] - 5s 187us/step - loss: 0.8847 - acc: 0.5943
Epoch 3/100
25010/25010 [==============================] - 5s 185us/step - loss: 0.8744 - acc: 0.6039
Epoch 4/100
25010/25010 [==============================] - 5s 185us/step - loss: 0.8685 - acc: 0.6064
Epoch 5/100
25010/25010 [==============================] - 5s 182us/step - loss: 0.8589 - acc: 0.6101
Epoch 6/100
25010/25010 [==============================] - 5s 185us/step - loss: 0.8500 - acc: 0.6182
Epoch 7/100
25010/25010 [==============================] - 5s 184us/step - loss: 0.8429 - acc: 0.6240
Epoch 8/100
25010/25010 [==============================] - 5s 182us/step - loss: 0.8317 - acc: 0.6267
Epoch 9/100
25010/25010 [==============================] - 5s 185us/step - loss: 0.8268 - acc: 0.6300
Epoch 10/100
25010/25010 [==============================] - 5s 187us/step - loss: 

25010/25010 [==============================] - 4s 161us/step - loss: 0.1578 - acc: 0.9594
Epoch 81/100
25010/25010 [==============================] - 4s 160us/step - loss: 0.1628 - acc: 0.9572
Epoch 82/100
25010/25010 [==============================] - 4s 161us/step - loss: 0.1529 - acc: 0.9586
Epoch 83/100
25010/25010 [==============================] - 4s 161us/step - loss: 0.1462 - acc: 0.9620
Epoch 84/100
25010/25010 [==============================] - 4s 160us/step - loss: 0.1931 - acc: 0.9505
Epoch 85/100
25010/25010 [==============================] - 4s 160us/step - loss: 0.1516 - acc: 0.9619
Epoch 86/100
25010/25010 [==============================] - 4s 160us/step - loss: 0.1611 - acc: 0.9568
Epoch 87/100
25010/25010 [==============================] - 4s 160us/step - loss: 0.1642 - acc: 0.9580
Epoch 88/100
25010/25010 [==============================] - 4s 162us/step - loss: 0.1759 - acc: 0.9543
Epoch 89/100
25010/25010 [==============================] - 4s 161us/step - loss: 0.14